import { cleanup, render, screen, waitFor } from '@testing-library/vue'
import userEvent from '@testing-library/user-event'
import { afterEach, expect, it, vi } from 'vitest'
import IncidentPackageReview from '../../src/renderer/src/components/IncidentPackageReview.vue'
import { createHronautI18n } from '../../src/renderer/src/i18n.js'
const draft = { draftId: 'draft', expiresAt: 'later', artifacts: [{ kind: 'repro', status: 'available', truncated: false }] }
function setup() {
  const api = { captureIncident: vi.fn(async () => draft), reviewIncident: vi.fn(async () => ({ previewId: 'preview', html: '<p>Reviewed</p>', sha256: 'hash', bytes: 15 })), discardIncident: vi.fn(async () => undefined), saveIncident: vi.fn(async () => ({ saved: true })) }
  vi.stubGlobal('hronaut', api)
  const view = render(IncidentPackageReview, { props: { tabId: 'tab' }, global: { plugins: [createHronautI18n('en-US')] } })
  return { api, view, user: userEvent.setup() }
}
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
it('requires selection, exact preview and explicit review; edits invalidate approval', async () => {
  const { api, user } = setup()
  await user.click(screen.getByText('Reviewed incident package'))
  expect(screen.getByRole('button', { name: 'Capture selected evidence' })).toBeDisabled()
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  const save = await screen.findByRole('button', { name: 'Save reviewed HTML' })
  expect(save).toBeDisabled()
  expect(screen.getByTitle('Preview exact package')).toHaveAttribute('sandbox', '')
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  await user.click(save)
  expect(api.saveIncident).toHaveBeenCalledWith({ draftId: 'draft', previewId: 'preview', reviewed: true })
  await user.type(screen.getByLabelText('Exact text to replace (optional)'), 'private')
  expect(screen.queryByRole('button', { name: 'Save reviewed HTML' })).toBeNull()
})
it('discards and ignores a late capture when closed', async () => {
  const { api, user, view } = setup()
  let resolve!: (value: typeof draft) => void
  api.captureIncident.mockImplementationOnce(() => new Promise(r => { resolve = r }))
  await user.click(screen.getByText('Reviewed incident package'))
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  view.unmount()
  resolve(draft)
  await waitFor(() => expect(api.discardIncident).toHaveBeenCalled())
  expect(api.reviewIncident).not.toHaveBeenCalled()
})

it.each(['capture', 'preview'] as const)('clears stale review when a replacement %s fails and requires fresh approval on recovery', async action => {
  const { api, user } = setup()
  await user.click(screen.getByText('Reviewed incident package'))
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  expect(screen.getByRole('button', { name: 'Save reviewed HTML' })).toBeEnabled()
  const method = action === 'capture' ? api.captureIncident : api.reviewIncident
  method.mockRejectedValueOnce(new Error('Replacement unavailable'))
  await user.click(screen.getByRole('button', { name: action === 'capture' ? 'Capture selected evidence' : 'Preview exact package' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Replacement unavailable')
  expect(screen.queryByTitle('Preview exact package')).toBeNull()
  expect(screen.queryByRole('button', { name: 'Save reviewed HTML' })).toBeNull()
  expect(api.saveIncident).not.toHaveBeenCalled()
  if (action === 'capture') {
    expect(screen.queryByRole('button', { name: 'Preview exact package' })).toBeNull()
    await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  }
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  expect(await screen.findByRole('button', { name: 'Save reviewed HTML' })).toBeDisabled()
  expect(screen.getByRole('checkbox', { name: /I reviewed this package/ })).not.toBeChecked()
})

it('sends exact field omission and invalidates an approved preview when it changes', async () => {
  const { api, user } = setup()
  await user.click(screen.getByText('Reviewed incident package'))
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.type(screen.getByLabelText('Exact JSON field name to omit (optional)'), 'url')
  await user.click(screen.getByRole('button', { name: 'Preview exact package' }))
  expect(api.reviewIncident).toHaveBeenLastCalledWith({ draftId: 'draft', include: ['repro'], omitFields: ['url'], replacements: [] })
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  await user.clear(screen.getByLabelText('Exact JSON field name to omit (optional)'))
  expect(screen.queryByTitle('Preview exact package')).toBeNull()
  expect(screen.queryByRole('button', { name: 'Save reviewed HTML' })).toBeNull()
})

it('clears a rejected save review but preserves approval when the file dialog is cancelled', async () => {
  const { api, user } = setup()
  await user.click(screen.getByText('Reviewed incident package'))
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  api.saveIncident.mockResolvedValueOnce({ saved: false })
  await user.click(screen.getByRole('button', { name: 'Save reviewed HTML' }))
  expect(screen.getByRole('button', { name: 'Save reviewed HTML' })).toBeEnabled()
  expect(screen.getByRole('checkbox', { name: /I reviewed this package/ })).toBeChecked()
  api.saveIncident.mockRejectedValueOnce(new Error('Incident review expired; capture again'))
  await user.click(screen.getByRole('button', { name: 'Save reviewed HTML' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Incident review expired; capture again')
  expect(screen.queryByTitle('Preview exact package')).toBeNull()
  expect(screen.queryByRole('button', { name: 'Save reviewed HTML' })).toBeNull()
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  expect(await screen.findByRole('button', { name: 'Save reviewed HTML' })).toBeDisabled()
  expect(screen.getByRole('checkbox', { name: /I reviewed this package/ })).not.toBeChecked()
})

it('ignores a late save rejection after a new capture and review', async () => {
  const { api, user } = setup()
  await user.click(screen.getByText('Reviewed incident package'))
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  let reject!: (error: Error) => void
  api.saveIncident.mockImplementationOnce(() => new Promise((_resolve, failure) => { reject = failure }))
  await user.click(screen.getByRole('button', { name: 'Save reviewed HTML' }))
  await user.click(screen.getByRole('button', { name: 'Discard review' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  await user.click(await screen.findByRole('button', { name: 'Preview exact package' }))
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  reject(new Error('Old save rejected'))
  await waitFor(() => expect(screen.getByRole('button', { name: 'Save reviewed HTML' })).toBeEnabled())
  expect(screen.getByTitle('Preview exact package')).toBeInTheDocument()
  expect(screen.queryByRole('alert')).toBeNull()
})

it('reviews multiple exact field omissions with bounded rows and keyboard focus', async () => {
  const { api, user } = setup()
  await user.click(screen.getByText('Reviewed incident package'))
  await user.click(screen.getByRole('checkbox', { name: 'Repro steps' }))
  await user.click(screen.getByRole('button', { name: 'Capture selected evidence' }))
  const fields = () => screen.getAllByLabelText('Exact JSON field name to omit (optional)')
  await user.type(fields()[0], 'url')
  const add = screen.getByRole('button', { name: 'Add field omission' })
  await user.click(add)
  expect(fields()[1]).toHaveFocus()
  await user.type(fields()[1], 'method')
  await user.click(add)
  await user.type(fields()[2], 'url')
  await user.click(add)
  await user.type(fields()[3], ' URL ')
  for (let row = 4; row < 10; row++) await user.click(add)
  expect(fields()).toHaveLength(10)
  expect(add).toBeDisabled()
  await user.click(screen.getByRole('button', { name: 'Preview exact package' }))
  expect(api.reviewIncident).toHaveBeenLastCalledWith({ draftId: 'draft', include: ['repro'], omitFields: ['url', 'method', ' URL '], replacements: [] })
  await user.click(screen.getByRole('checkbox', { name: /I reviewed this package/ }))
  await user.click(screen.getByRole('button', { name: 'Remove field omission 2' }))
  expect(fields()[1]).toHaveFocus()
  expect(fields()).toHaveLength(9)
  expect(add).toBeEnabled()
  expect(screen.queryByTitle('Preview exact package')).toBeNull()
  expect(screen.queryByRole('button', { name: 'Save reviewed HTML' })).toBeNull()
  await user.click(screen.getByRole('button', { name: 'Preview exact package' }))
  expect(api.reviewIncident).toHaveBeenLastCalledWith({ draftId: 'draft', include: ['repro'], omitFields: ['url', ' URL '], replacements: [] })
  expect(await screen.findByRole('button', { name: 'Save reviewed HTML' })).toBeDisabled()
})
