import { expect, test } from './fixtures.js'

const primaryModifier = process.platform === 'darwin' ? 'Meta' : 'Control'

test('finds global and website commands from the accessible command palette', async ({ appWindow, electronApp }) => {
  const commandButton = appWindow.getByRole('button', { name: 'Open command palette' })
  await expect(commandButton).toBeVisible()
  await commandButton.click()

  let palette = appWindow.getByRole('dialog', { name: 'Commands' })
  await expect(palette).toBeVisible()
  const commandSearch = palette.getByRole('combobox', { name: 'Search commands' })
  await expect(commandSearch).toBeFocused()
  await commandSearch.fill('screenshot')
  await expect(palette.getByText('No matching commands')).toBeVisible()
  await commandSearch.fill('settings')
  await expect(palette.getByRole('option', { name: /Open Settings/ })).toBeVisible()
  await commandSearch.press('Enter')
  await expect(appWindow.getByRole('dialog', { name: 'Settings' })).toBeVisible()
  await appWindow.getByRole('dialog', { name: 'Settings' }).getByRole('button', { name: 'Close settings' }).click()

  await appWindow.getByRole('button', { name: 'New tab' }).click()
  await commandButton.click()
  palette = appWindow.getByRole('dialog', { name: 'Commands' })
  await palette.getByRole('combobox', { name: 'Search commands' }).fill('clipboard image')
  await expect(palette.getByRole('option', { name: /Capture area screenshot/ })).toBeVisible()
  await expect(palette.getByRole('option', { name: /Capture element screenshot/ })).toBeVisible()
  await expect(palette.getByRole('option', { name: /Capture viewport screenshot/ })).toBeVisible()
  await expect(palette.getByRole('option', { name: /Capture full-page screenshot/ })).toBeVisible()
  await appWindow.keyboard.press('Escape')
  await expect(palette).toBeHidden()

  await electronApp.evaluate(({ clipboard }) => clipboard.clear())
  await commandButton.click()
  palette = appWindow.getByRole('dialog', { name: 'Commands' })
  await palette.getByRole('combobox', { name: 'Search commands' }).fill('visible screen')
  await palette.getByRole('option', { name: /Capture viewport screenshot/ }).click()
  await expect(appWindow.getByRole('button', { name: 'Viewport screenshot copied — paste it into agent chat' })).toBeVisible()
  expect(await electronApp.evaluate(({ clipboard }) => clipboard.readImage().isEmpty())).toBe(false)

  await electronApp.evaluate(({ clipboard }) => clipboard.clear())
  await commandButton.click()
  palette = appWindow.getByRole('dialog', { name: 'Commands' })
  await palette.getByRole('combobox', { name: 'Search commands' }).fill('page context headings controls')
  await palette.getByRole('option', { name: /Copy page snapshot for agent/ }).click()
  await expect(appWindow.getByRole('status', { name: 'Page snapshot copied' })).toBeVisible()
  expect(await electronApp.evaluate(({ clipboard }) => clipboard.readText())).toContain('URL:')

  await commandButton.click()
  palette = appWindow.getByRole('dialog', { name: 'Commands' })
  await palette.getByRole('combobox', { name: 'Search commands' }).fill('timeout override request')
  await palette.getByRole('option', { name: /Open Request conditions/ }).click()
  const networkPanel = appWindow.getByRole('dialog', { name: 'Network' })
  await expect(networkPanel.getByRole('region', { name: 'Request conditions' })).toBeVisible()
  await expect(networkPanel.getByRole('button', { name: /Request conditions/ })).toHaveAttribute('aria-expanded', 'true')
  await networkPanel.getByRole('button', { name: 'Close network monitor' }).click()

  await appWindow.keyboard.press(`${primaryModifier}+Shift+P`)
  palette = appWindow.getByRole('dialog', { name: 'Commands' })
  await expect(palette).toBeVisible()
  await palette.getByRole('combobox', { name: 'Search commands' }).fill('cookies cache')
  await expect(palette.getByRole('option', { name: /Open Privacy & data/ })).toBeVisible()
  await palette.getByRole('combobox', { name: 'Search commands' }).press('Enter')
  const settings = appWindow.getByRole('dialog', { name: 'Settings' })
  await expect(settings.getByRole('heading', { name: 'Privacy & browsing data' })).toBeVisible()
  await settings.getByRole('button', { name: 'Close settings' }).click()

  await appWindow.keyboard.press(`${primaryModifier}+Shift+P`)
  palette = appWindow.getByRole('dialog', { name: 'Commands' })
  const paletteSearch = palette.getByRole('combobox', { name: 'Search commands' })
  const initiallySelected = await palette.locator('[role="option"][aria-selected="true"]').getAttribute('id')
  await paletteSearch.press('ArrowDown')
  await expect.poll(async () => palette.locator('[role="option"][aria-selected="true"]').getAttribute('id')).not.toBe(initiallySelected)
  await paletteSearch.fill('new tab')
  await expect(palette.getByRole('option', { name: /New tab/ })).toHaveAttribute('aria-selected', 'true')
  await paletteSearch.press('Enter')
  await expect(appWindow.getByRole('tab')).toHaveCount(2)
})

test('preserves a selected global command when live tab state removes website commands', async ({ appWindow }) => {
  await appWindow.getByRole('button', { name: 'New tab' }).click()
  await expect(appWindow.locator('.toolbar')).toBeVisible()
  await appWindow.getByRole('button', { name: 'Open command palette' }).click()

  const palette = appWindow.getByRole('dialog', { name: 'Commands' })
  const settingsCommand = palette.getByRole('option', { name: /Open Settings/ })
  await settingsCommand.hover()
  await expect(palette.locator('[role="option"][aria-selected="true"]')).toHaveAttribute('id', 'command-palette-settings')
  await expect(palette.getByRole('option', { name: /Capture area screenshot/ })).toBeVisible()

  await appWindow.evaluate('window.hronaut.openHome()')
  await expect(appWindow.locator('.toolbar')).toBeHidden()
  await expect(palette.getByRole('option', { name: /Capture area screenshot/ })).toHaveCount(0)
  await expect(palette.locator('[role="option"][aria-selected="true"]')).toHaveAttribute('id', 'command-palette-settings')
  await expect(palette.getByRole('combobox', { name: 'Search commands' })).toBeFocused()

  await palette.getByRole('combobox', { name: 'Search commands' }).press('Enter')
  await expect(appWindow.getByRole('dialog', { name: 'Settings' })).toBeVisible()
})
