import type { ReactInspectionResult } from '../../src/shared/react-inspection.js'
import type { HronautApi, HronautMcpApi, HronautSettingsApi } from '../../src/shared/types.js'
import { decode, expect, rejected, test, type Workspace } from './react-inspection-fixtures.js'

test('React actions leave a sleeping tab asleep even when following agent activity is enabled', async ({ react, appWindow }) => {
  const selected = await react.success<{activeTabId: string}>(react.call('browser_new_tab', {
    workspaceId: react.workspace.id, url: react.origin + '/keep-selected'
  }))
  await appWindow.evaluate(async ({ targetId, selectedId }) => {
    const { hronaut, hronautSettings } = window as unknown as {hronaut: HronautApi; hronautSettings: HronautSettingsApi}
    await hronaut.selectTab(selectedId)
    await hronaut.setTabSleeping(targetId, true)
    await hronautSettings.setFollowAgentActivity(true)
  }, { targetId: react.tabId, selectedId: selected.activeTabId })
  for (const action of ['status', 'enable', 'tree', 'disable'] as const) {
    await react.react(action)
    const state = await appWindow.evaluate(() => (window as unknown as {hronaut: HronautApi}).hronaut.getState())
    expect(state.tabs.find(tab => tab.id === react.tabId)?.sleeping).toBe(true)
    expect(state.activeTabId).toBe(selected.activeTabId)
  }
})

test('explicit MCP and native opt-in preserves isolation, subtree identity and navigation semantics', async ({ react, appWindow }) => {
  const { workspace, tabId, page } = react
  expect(await page.evaluate('fixtureSawHook')).toBe(false)
  expect((await react.readMenu()).enabled).toBe(false)
  await react.toggleMenu()
  await expect.poll(async () => (await react.success<ReactInspectionResult>(react.react('status'))).status).toBe('reload-required')
  expect(await page.evaluate('fixtureSawHook')).toBe(false)
  expect((await react.readMenu()).label).toContain('reload')
  await react.navigate('/native-enabled')
  expect(await page.evaluate('fixtureSawHook')).toBe(true)
  const first = await react.success<ReactInspectionResult>(react.react('tree'))
  expect(first.status).toBe('ready')
  const named = first.nodes.find(node => node.name === 'Named')!
  const subtree = await react.success<ReactInspectionResult>(react.react('tree', named.id))
  expect(subtree.nodes.map(node => node.name)).toEqual(['Named', 'Nested'])
  expect(subtree.nodes[0]?.parent).toBeNull()
  expect(rejected(await react.react('tree', named.id + '-invalid'))).toBe(true)
  const other = await react.success<Workspace>(react.call('browser_workspaces', { action: 'create', storage: 'scratch', name: 'React other' }))
  const otherTab = (await react.success<{activeTabId: string}>(react.call('browser_new_tab', { workspaceId: other.id, url: react.origin + '/other' }))).activeTabId
  expect((await react.call('browser_react', { workspaceId: other.id, tabId, action: 'tree' })).isError).toBe(true)
  expect((await react.success<ReactInspectionResult>(react.call('browser_react', { workspaceId: other.id, tabId: otherTab, action: 'status' }))).status).toBe('disabled')
  await expect(appWindow.evaluate(({ a, b }) => (window as unknown as {hronaut: HronautApi}).hronaut.reorderTab(a, b, 'before'), { a: tabId, b: otherTab })).rejects.toThrow()
  await page.evaluate('fixtureRender("empty");void 0')
  await expect(page.locator('span')).toHaveCount(0)
  expect(rejected(await react.react('tree', named.id))).toBe(true)
  await page.evaluate('fixtureRender("normal");void 0')
  await expect(page.locator('span')).toHaveCount(1)
  expect(rejected(await react.react('tree', named.id))).toBe(true)
  const beforeHash = await react.success<ReactInspectionResult>(react.react('tree'))
  await page.evaluate('location.hash="changed";void 0')
  await expect.poll(async () => (await react.success<ReactInspectionResult>(react.react('status'))).navigationGeneration).not.toBe(beforeHash.navigationGeneration)
  expect((await react.success<ReactInspectionResult>(react.react('tree'))).installationId).toBe(beforeHash.installationId)
  expect(rejected(await react.react('tree', beforeHash.nodes[0]!.id))).toBe(true)
  await react.navigate('/next-document')
  expect((await react.success<ReactInspectionResult>(react.react('tree'))).installationId).not.toBe(first.installationId)
  expect(rejected(await react.react('tree', first.nodes[0]!.id))).toBe(true)
  await react.toggleMenu()
  await expect.poll(async () => (await react.success<ReactInspectionResult>(react.react('status'))).status).toBe('disabled-reload-required')
  await expect.poll(() => page.evaluate('__hronautReactInspection.status().state')).toBe('disabled-reload-required')
  expect((await react.readMenu()).label).toContain('residue')
  await react.navigate('/off-again')
  expect(await page.evaluate('fixtureSawHook')).toBe(false)
  expect((await react.success<ReactInspectionResult>(react.react('status'))).status).toBe('disabled')
  expect(workspace.id).not.toBe(other.id)
})

test('repeated enable preserves truthful native residue status without reviving old observations', async ({ react }) => {
  const installed = await react.enable('/repeat-enable')
  expect(installed.status).toBe('ready')
  const enabled = await react.success<ReactInspectionResult>(react.react('enable'))
  expect(enabled).toMatchObject({ status: 'reload-required', reloadRequired: true })
  expect(enabled.installationId).toBeUndefined()
  const old = await react.success<ReactInspectionResult>(react.react('tree', installed.nodes[0]!.id))
  expect(old.status).not.toBe('ready')
  expect(old.nodes).toEqual([])
  await react.toggleMenu()
  expect(await react.success<ReactInspectionResult>(react.react('status'))).toMatchObject({ status: 'disabled-reload-required', enabled: false, reloadRequired: true })
  expect((await react.readMenu()).label).toContain('residue')
  await expect.poll(() => react.page.evaluate('__hronautReactInspection.status().state')).toBe('disabled-reload-required')
  await react.page.evaluate('__REACT_DEVTOOLS_GLOBAL_HOOK__.inject({});__REACT_DEVTOOLS_GLOBAL_HOOK__.onCommitFiberRoot(1,{current:null});void 0')
  expect(await react.page.evaluate('({roots:__hronautReactInspection.status().roots,renderers:__hronautReactInspection.status().renderers})')).toEqual({ roots: 0, renderers: 0 })
  // A native re-arm of the disabled document also retains its residue warning.
  await react.toggleMenu()
  await expect.poll(async () => (await react.success<ReactInspectionResult>(react.react('status'))).status).toBe('reload-required')
  await react.toggleMenu()
  expect((await react.success<ReactInspectionResult>(react.react('status'))).status).toBe('disabled-reload-required')
  await react.navigate('/repeat-disabled-new-document')
  expect(await react.success<ReactInspectionResult>(react.react('status'))).toMatchObject({ status: 'disabled', reloadRequired: false })
  expect((await react.readMenu()).label).toBe('Off')
  expect(await react.page.evaluate('fixtureSawHook')).toBe(false)
})

test('pause, workspace permission roundtrips and lease changes invalidate pending reads and old IDs', async ({ react, appWindow }) => {
  const first = await react.enable()
  await react.holdRead()
  const pending = react.react('tree')
  await react.entered()
  await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.setPaused(true))
  await react.release()
  expect(rejected(await pending)).toBe(true)
  await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.setPaused(false))
  await react.success(react.call('browser_workspaces', { action: 'claim-ownership', workspaceId: react.workspace.id }))
  expect(rejected(await react.react('tree', first.nodes[0]!.id))).toBe(true)
  const fresh = await react.success<ReactInspectionResult>(react.react('tree'))
  expect(fresh.status).toBe('ready')
  await react.success(react.call('browser_workspaces', { action: 'release-ownership', workspaceId: react.workspace.id }))
  await react.success(react.call('browser_workspaces', { action: 'claim-ownership', workspaceId: react.workspace.id }))
  expect(rejected(await react.react('tree', fresh.nodes[0]!.id))).toBe(true)
  const beforeRevoke = await react.success<ReactInspectionResult>(react.react('tree'))
  await react.holdRead()
  const revoked = react.react('tree')
  await react.entered()
  await appWindow.evaluate(id => (window as unknown as {hronaut: HronautApi}).hronaut.updateTabGroup(id, { agentAccess: false }), react.workspace.id)
  await appWindow.evaluate(id => (window as unknown as {hronaut: HronautApi}).hronaut.updateTabGroup(id, { agentAccess: true }), react.workspace.id)
  await react.release()
  expect(rejected(await revoked)).toBe(true)
  expect(rejected(await react.react('tree', beforeRevoke.nodes[0]!.id))).toBe(true)
  expect((await react.success<ReactInspectionResult>(react.react('tree'))).status).toBe('ready')
  await react.navigate('/revoked-installation')
  expect(await react.page.evaluate('fixtureSawHook')).toBe(false)
})

test('caller timeout retains native serialization and debugger ownership is respected', async ({ react, electronApp, appWindow }) => {
  await react.enable()
  await react.success(react.call('browser_code_coverage', { workspaceId: react.workspace.id, tabId: react.tabId, action: 'start', reload: false }))
  expect(rejected(await react.react('tree'))).toBe(true)
  await react.success(react.call('browser_code_coverage', { workspaceId: react.workspace.id, tabId: react.tabId, action: 'stop' }))
  await react.holdRead()
  const pending = react.react('tree')
  await react.entered()
  expect(decode<ReactInspectionResult>(await pending).status).toBe('timed-out')
  const queued = react.react('tree')
  await react.release()
  expect((await react.success<ReactInspectionResult>(queued)).status).toBe('ready')
  expect(await electronApp.evaluate(async ({ webContents }, id) => {
    const objectId = (globalThis as typeof globalThis & {__reactHold?: {objectId?: string}}).__reactHold?.objectId
    if (!objectId) return false
    try { await webContents.fromId(id)!.debugger.sendCommand('Runtime.getProperties', { objectId }); return false } catch { return true }
  }, react.contentsId)).toBe(true)
  await react.holdRead()
  const openingRead = react.react('tree')
  await react.entered()
  const opening = appWindow.evaluate(id => (window as unknown as {hronaut: HronautApi}).hronaut.toggleDevTools(id), react.tabId)
  // A second trusted IPC roundtrip observes dispatch of the preceding UI request.
  await appWindow.evaluate(() => (window as unknown as {hronaut: HronautApi}).hronaut.getState())
  await react.release()
  expect(rejected(await openingRead)).toBe(true)
  await opening
  expect(rejected(await react.react('tree'))).toBe(true)
  expect(await electronApp.evaluate(({ webContents }, id) => webContents.fromId(id)!.debugger.isAttached(), react.contentsId)).toBe(false)
  await appWindow.evaluate(id => (window as unknown as {hronaut: HronautApi}).hronaut.toggleDevTools(id), react.tabId)
  await react.enable('/after-devtools')
  await react.holdRead()
  const detached = react.react('tree')
  await react.entered()
  await electronApp.evaluate(({ webContents }, id) => webContents.fromId(id)!.debugger.detach(), react.contentsId)
  await react.release()
  expect(rejected(await detached)).toBe(true)
})

test('authentication generation roundtrip and capability rotation reject in-flight observations', async ({ react, appWindow, mcpToken }) => {
  await appWindow.evaluate(() => (window as unknown as {hronautSettings: HronautSettingsApi}).hronautSettings.setMcpAuthentication(true))
  await react.reconnect(mcpToken)
  await react.success(react.call('browser_workspaces', { action: 'resume', workspaceId: react.workspace.id, resumeKey: react.workspace.resumeKey }))
  const before = await react.enable()
  await react.holdRead()
  const pending = react.react('tree').then(rejected, () => true)
  await react.entered()
  await appWindow.evaluate(() => (window as unknown as {hronautSettings: HronautSettingsApi}).hronautSettings.setMcpAuthentication(false))
  await react.release()
  expect(await pending).toBe(true)
  await appWindow.evaluate(() => (window as unknown as {hronautSettings: HronautSettingsApi}).hronautSettings.setMcpAuthentication(true))
  await expect(react.client.listTools()).rejects.toThrow()
  await react.reconnect(mcpToken)
  await react.success(react.call('browser_workspaces', { action: 'resume', workspaceId: react.workspace.id, resumeKey: react.workspace.resumeKey }))
  expect(rejected(await react.react('tree', before.nodes[0]!.id))).toBe(true)
  await react.success(react.call('browser_workspaces', { action: 'release-ownership', workspaceId: react.workspace.id }))
  let profile = await appWindow.evaluate(() => (window as unknown as {hronautSettings: HronautSettingsApi}).hronautSettings.createMcpCapabilityProfile({ name: 'React credential', preset: 'complete', expiresInMinutes: 60 }))
  await react.reconnect(profile.credential)
  await react.success(react.call('browser_workspaces', { action: 'resume', workspaceId: react.workspace.id, resumeKey: react.workspace.resumeKey }))
  for (const change of ['rotate', 'update']) {
    const old = await react.success<ReactInspectionResult>(react.react('tree'))
    await react.holdRead()
    const inFlight = react.react('tree').then(rejected, () => true)
    await react.entered()
    profile = await appWindow.evaluate(({ id, change, workspaceId }) => {
      const settings = (window as unknown as {hronautSettings: HronautSettingsApi}).hronautSettings
      return change === 'rotate' ? settings.rotateMcpCapabilityProfile(id)
        : settings.updateMcpCapabilityProfile(id, { name: 'React scoped credential', preset: 'complete', expiresInMinutes: 60, workspaceIds: [workspaceId] })
    }, { id: profile.profile.id, change, workspaceId: react.workspace.id })
    await react.release()
    expect(await inFlight).toBe(true)
    await expect(react.client.listTools()).rejects.toThrow()
    await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.setPaused(true))
    await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.setPaused(false))
    await react.reconnect(profile.credential)
    await react.success(react.call('browser_workspaces', { action: 'resume', workspaceId: react.workspace.id, resumeKey: react.workspace.resumeKey }))
    expect(rejected(await react.react('tree', old.nodes[0]!.id))).toBe(true)
    expect((await react.success<ReactInspectionResult>(react.react('tree'))).status).toBe('ready')
  }
})

test('paused admission cannot install later after a timed-out native command releases the queue', async ({ react, appWindow }) => {
  await react.enable()
  await react.holdRead()
  const held = react.react('tree')
  await react.entered()
  expect(decode<ReactInspectionResult>(await held).status).toBe('timed-out')
  await react.success(react.react('disable'))
  const pendingEnable = react.react('enable')
  await expect.poll(async () => (await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.getState())).activeCommands ?? 0).toBeGreaterThan(0)
  await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.setPaused(true))
  await react.release()
  expect(rejected(await pendingEnable)).toBe(true)
  await appWindow.evaluate(() => (window as unknown as {hronautMcp: HronautMcpApi}).hronautMcp.setPaused(false))
  await react.success(react.call('browser_workspaces', {action:'claim-ownership',workspaceId:react.workspace.id}))
  await react.navigate('/after-rejected-enable')
  expect(await react.page.evaluate('fixtureSawHook')).toBe(false)
})

test('root unmount and close invalidate IDs without retargeting', async ({ react }) => {
  const before = await react.enable()
  await react.page.evaluate('fixtureUnmount();void 0')
  await expect(react.page.locator('span')).toHaveCount(0)
  expect(rejected(await react.react('tree', before.nodes[0]!.id))).toBe(true)
  await react.success(react.call('browser_close_tab', {workspaceId:react.workspace.id,tabId:react.tabId}))
  expect(rejected(await react.react('tree', before.nodes[0]!.id))).toBe(true)
})
