import { expect, test } from './fixtures.js'

test('toggles Settings with the gear and keeps search, reset and close in the header', async ({ appWindow }, testInfo) => {
  await appWindow.getByRole('button', { name: 'Settings', exact: true }).click()
  const settings = appWindow.getByRole('tabpanel', { name: 'Settings', exact: true })
  await settings.getByRole('combobox', { name: 'Tab position' }).selectOption('left')
  await expect(appWindow.locator('.shell-title-bar-surface.surface-settings')).toHaveText('Settings')
  await expect(appWindow.locator('.settings-footer')).toHaveCount(0)
  await expect(appWindow.locator('.settings-tab-close')).toHaveCount(0)
  const gear = appWindow.getByRole('button', { name: 'Settings', exact: true })
  await expect(gear).toHaveAttribute('aria-pressed', 'true')
  await expect(appWindow.getByRole('tab', { name: 'Settings', exact: true })).toHaveCount(0)
  await expect(settings.locator('.settings-header').getByRole('searchbox')).toBeVisible()
  await expect(settings.locator('.settings-header').getByRole('heading')).toHaveCount(0)
  await expect(settings.locator('.settings-header').getByRole('button', { name: 'Reset to default' })).toBeVisible()
  await gear.click()
  await expect(settings).toBeHidden()
  await expect(gear).toHaveAttribute('aria-pressed', 'false')
  await gear.click()
  await expect(settings).toBeVisible()
  const search = settings.getByRole('searchbox')
  await search.fill('download')
  await search.press('Enter')
  await expect(settings.getByRole('button', { name: /Downloads/ })).toHaveAttribute('aria-current', 'page')
  await search.press('Escape')
  await expect(search).toHaveValue('')
  await expect(settings).toBeVisible()
  await settings.getByRole('button', { name: /Appearance/ }).click()
  await appWindow.setViewportSize({ width: 1900, height: 1040 })
  await expect.poll(() => settings.locator('.settings-content').evaluate(element => element.clientWidth)).toBeLessThanOrEqual(1164)
  await appWindow.screenshot({ path: testInfo.outputPath('settings-utility-layout.png') })
  await settings.getByRole('button', { name: 'Close settings', exact: true }).click()
  await expect(settings).toBeHidden()
  await expect(appWindow.getByRole('button', { name: 'Settings', exact: true })).toBeVisible()
})
