import { createServer } from 'node:http'
import type { HronautApi } from '../../src/shared/types.js'
import { closeFixtureServer, expect, test } from './fixtures.js'

test('filters mixed tab-search results and restores only the selected result kind', async ({ appWindow, electronApp }, testInfo) => {
  const server = createServer((request, response) => {
    const label = request.url === '/saved' ? 'saved' : request.url === '/closed' ? 'closed' : 'open'
    response.writeHead(200, { 'content-type': 'text/html', 'cache-control': 'no-store' })
    response.end(`<!doctype html><title>Shared ${label}</title><main>Shared ${label} synthetic fixture</main>`)
  })
  await new Promise<void>((resolve, reject) => {
    server.once('error', reject)
    server.listen(0, '127.0.0.1', resolve)
  })
  try {
    const address = server.address()
    if (!address || typeof address === 'string') throw new Error('Fixture server unavailable')
    const base = `http://127.0.0.1:${address.port}`
    const created = await appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.createWorkspace({ name: 'Shared archive', storage: 'scratch' }))
    const group = created.mcpTabGroups.find(item => item.name === 'Shared archive')!
    await appWindow.evaluate(args => (window as unknown as { hronaut: HronautApi }).hronaut.navigate(args), { tabId: created.activeTabId!, url: `${base}/saved` })
    await expect.poll(() => appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.getState().then(state => state.tabs.some(tab => tab.title === 'Shared saved' && !tab.loading)))).toBe(true)
    await appWindow.evaluate(id => (window as unknown as { hronaut: HronautApi }).hronaut.saveAndCloseTabGroup(id), group.id)
    await appWindow.evaluate(url => (window as unknown as { hronaut: HronautApi }).hronaut.newTab({ url, active: true }), `${base}/open`)
    await appWindow.evaluate(url => (window as unknown as { hronaut: HronautApi }).hronaut.newTab({ url, active: false }), `${base}/closed`)
    await expect.poll(() => appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.getState().then(state => state.tabs.filter(tab => tab.title.startsWith('Shared ') && !tab.loading).length))).toBe(2)
    const beforeClose = await appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.getState())
    const closed = beforeClose.tabs.find(tab => tab.url === `${base}/closed`)!
    await appWindow.evaluate(id => (window as unknown as { hronaut: HronautApi }).hronaut.closeTab(id), closed.id)
    const beforeFilter = await appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.getState())
    await appWindow.getByRole('button', { name: 'Search tabs', exact: true }).click()
    const panel = appWindow.getByRole('dialog', { name: 'Tabs', exact: true })
    const search = panel.getByRole('searchbox')
    const kind = panel.getByRole('combobox', { name: 'Result type' })
    await search.fill('shared')
    await expect(panel.locator('.tab-overview-card')).toHaveCount(1)
    await expect(panel.locator('.saved-group')).toHaveCount(1)
    await expect(panel.locator('.tab-search-item.closed')).toHaveCount(1)
    await search.fill('127.0.0.1   SHARED')
    await expect(panel.locator('.tab-overview-card')).toHaveCount(1)
    await expect(panel.locator('.saved-group')).toHaveCount(1)
    await expect(panel.locator('.tab-search-item.closed')).toHaveCount(1)
    await kind.focus()
    await kind.press('Home')
    await kind.press('ArrowDown')
    await kind.press('Enter')
    await expect(kind).toHaveValue('open')
    await expect(kind).toBeFocused()
    await expect(panel.locator('.saved-group, .tab-search-item.closed')).toHaveCount(0)
    await kind.selectOption('saved')
    await expect(panel.locator('.saved-group')).toHaveCount(1)
    await expect(panel.locator('.tab-overview-card, .tab-search-item.closed')).toHaveCount(0)
    await search.fill('archive 127.0.0.1')
    await expect(panel.locator('.saved-group')).toHaveCount(1)
    await search.fill('127.0.0.1 shared')
    await kind.selectOption('closed')
    await expect(panel.locator('.tab-search-item.closed')).toHaveCount(1)
    await expect(panel.locator('.tab-overview-card, .saved-group')).toHaveCount(0)
    const afterFilter = await appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.getState())
    expect(afterFilter.tabs.map(tab => tab.id)).toEqual(beforeFilter.tabs.map(tab => tab.id))
    expect(afterFilter.activeTabId).toBe(beforeFilter.activeTabId)
    expect(afterFilter.closedTabs).toEqual(beforeFilter.closedTabs)
    expect(afterFilter.savedTabGroups).toEqual(beforeFilter.savedTabGroups)
    await search.fill('missing')
    await expect(panel).toContainText('No matching tabs')
    await expect(search).not.toHaveAttribute('aria-activedescendant')
    await search.fill('shared')
    await electronApp.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]!.setSize(760, 760))
    await expect(kind).toBeInViewport({ ratio: 1 })
    expect(await panel.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
    await testInfo.attach('tab-search-kind-compact', { body: await panel.screenshot(), contentType: 'image/png' })
    await search.press('Enter')
    await expect(panel).toHaveCount(0)
    await expect.poll(() => appWindow.evaluate(() => (window as unknown as { hronaut: HronautApi }).hronaut.getState().then(state => state.tabs.find(tab => tab.active)?.title))).toBe('Shared closed')
    await appWindow.getByRole('button', { name: 'Search tabs', exact: true }).click()
    await expect(kind).toHaveValue('all')
    await expect(search).toHaveValue('')
    await kind.selectOption('saved')
    await search.fill('shared')
    await search.press('Enter')
    await expect(panel).toHaveCount(0)
    await expect.poll(() => appWindow.evaluate(id => (window as unknown as { hronaut: HronautApi }).hronaut.getState().then(state => state.mcpTabGroups.some(group => group.id === id) && !state.savedTabGroups.some(group => group.id === id)), group.id)).toBe(true)
  } finally { await closeFixtureServer(server) }
})
