import type { BrowserReproRecording, BrowserReproStep } from './types.js'
import { javascriptLiteral } from './javascript-literal.js'

function quoted(value: string): string {
  return javascriptLiteral(value)
}

function playwrightKey(key: string): string {
  return key
    .split('+')
    .map((part) => part === 'Ctrl' ? 'Control' : part)
    .join('+')
}

function targetExpression(step: BrowserReproStep): string | null {
  return step.target?.selector ? `page.locator(${quoted(step.target.selector)})` : null
}

export function formatReproAsPlaywright(recording: BrowserReproRecording): string {
  const lines = [
    "import { test } from '@playwright/test'",
    '',
    '// Generated by Hronaut from a privacy-safe human reproduction timeline.',
    '// Review selectors, provide redacted inputs through environment variables, and add assertions before running.',
    ...(recording.active ? ['// WARNING: The recording was still active when this skeleton was exported.'] : []),
    ...(recording.truncated ? ['// WARNING: The recording reached its step limit, so the flow is incomplete.'] : []),
    `test(${quoted(`reproduce: ${recording.title || 'recorded issue'}`)}, async ({ page }) => {`
  ]

  if (!recording.steps.length) lines.push('  // TODO: Record the reproduction steps before running this test.')

  for (const step of recording.steps) {
    const target = targetExpression(step)
    if (step.kind === 'navigate') {
      lines.push(`  await page.goto(${quoted(step.url)})`)
    } else if (step.kind === 'click' && target) {
      lines.push(`  await ${target}.click()`)
    } else if (step.kind === 'input' && target) {
      const variable = `reproInput${step.index}`
      const environmentName = `HRONAUT_REPRO_INPUT_${step.index}`
      lines.push(
        `  const ${variable} = process.env.${environmentName}`,
        `  if (${variable} === undefined) throw new Error(${quoted(`Set ${environmentName} to a safe test value before running this reproduction`)})`,
        `  await ${target}.fill(${variable})`
      )
    } else if (step.kind === 'key' && step.key) {
      const action = `${target ?? 'page.keyboard'}.press(${quoted(playwrightKey(step.key))})`
      lines.push(`  await ${action}`)
    } else if (step.kind === 'scroll' && step.scroll) {
      lines.push(`  await page.evaluate(({ x, y }) => window.scrollTo(x, y), ${javascriptLiteral(step.scroll)})`)
    } else {
      lines.push(`  // TODO: Recreate step ${step.index}: ${step.kind}`)
    }
  }

  lines.push(
    '',
    `  throw new Error(${quoted('TODO: replace this line with an assertion for the expected failure or corrected behavior')})`,
    '})',
    ''
  )
  return lines.join('\n')
}
