import type { BrowserReproRecording, BrowserReproStep } from './types.js'
import { javascriptLiteral } from './javascript-literal.js'

function quoted(value: string): string {
  return javascriptLiteral(value)
}

function playwrightKey(key: string): string {
  return key
    .split('+')
    .map((part) => part === 'Ctrl' ? 'Control' : part)
    .join('+')
}

function targetExpression(step: BrowserReproStep): string | null {
  // Recording validates selectors with document.querySelectorAll. Plain
  // Playwright CSS also pierces shadow roots and can select additional nodes.
  return step.target?.selector ? `page.locator(${quoted(`css:light=${step.target.selector}`)})` : null
}

export function formatReproAsPlaywright(recording: BrowserReproRecording): string {
  const supportedExpectation = (step: BrowserReproStep) => step.kind === 'expect' && Boolean(step.target?.selector)
    && (step.expectation?.condition === 'visible' || step.expectation?.condition === 'hidden' || step.expectation?.condition === 'checked' || step.expectation?.condition === 'unchecked'
      || (step.expectation?.condition === 'text' && typeof step.expectation.text === 'string'))
  const lines = [
    recording.steps.some(step => step.expectation) ? "import { test, expect } from '@playwright/test'" : "import { test } from '@playwright/test'",
    '',
    '// Generated by Hronaut from a privacy-safe human reproduction timeline.',
    '// Review selectors, provide redacted inputs through environment variables, and add assertions before running.',
    ...(recording.active ? ['// WARNING: The recording was still active when this skeleton was exported.'] : []),
    ...(recording.truncated ? ['// WARNING: The recording reached its step limit, so the flow is incomplete.'] : []),
    `test(${quoted(`reproduce: ${recording.title || 'recorded issue'}`)}, async ({ page }) => {`
  ]

  if (!recording.steps.length) lines.push('  // TODO: Record the reproduction steps before running this test.')

  for (const step of recording.steps) {
    const target = targetExpression(step)
    if (step.kind === 'expect' && target && step.expectation) {
      const expectation = step.expectation
      if (expectation.condition === 'text' && typeof expectation.text === 'string') {
        lines.push(`  await expect(${target}).toHaveText(${quoted(expectation.text)})`)
      } else if (expectation.condition === 'visible' || expectation.condition === 'hidden') {
        lines.push(`  await expect(${target}).${expectation.condition === 'visible' ? 'toBeVisible' : 'toBeHidden'}()`)
      } else if (expectation.condition === 'checked' || expectation.condition === 'unchecked') {
        lines.push(`  await expect(${target}).${expectation.condition === 'unchecked' ? 'not.' : ''}toBeChecked()`)
      } else {
        lines.push(`  // TODO: Recreate unsupported expectation at step ${step.index}`)
      }
    } else if (step.kind === 'navigate') {
      lines.push(`  await page.goto(${quoted(step.url)})`)
    } else if (step.kind === 'click' && target) {
      lines.push(`  await ${target}.click()`)
    } else if (step.kind === 'input' && target) {
      const variable = `reproInput${step.index}`
      const environmentName = `HRONAUT_REPRO_INPUT_${step.index}`
      lines.push(
        `  const ${variable} = process.env.${environmentName}`,
        `  if (${variable} === undefined) throw new Error(${quoted(`Set ${environmentName} to a safe test value before running this reproduction`)})`,
        `  await ${target}.fill(${variable})`
      )
    } else if (step.kind === 'key' && step.key && (!step.target || target)) {
      const action = `${target ?? 'page.keyboard'}.press(${quoted(playwrightKey(step.key))})`
      lines.push(`  await ${action}`)
    } else if (step.kind === 'scroll' && step.scroll) {
      lines.push(`  await page.evaluate(({ x, y }) => window.scrollTo(x, y), ${javascriptLiteral(step.scroll)})`)
    } else {
      lines.push(`  // TODO: Recreate step ${step.index}: ${step.kind}`)
    }
  }

  lines.push(
    '',
    ...(recording.steps.some(supportedExpectation)
      ? []
      : [`  throw new Error(${quoted('TODO: replace this line with an assertion for the expected failure or corrected behavior')})`]),
    '})',
    ''
  )
  return lines.join('\n')
}
