import type { BrowserReproRecording, BrowserReproStep } from './types.js'
import { validReproCount, validReproCountSelector } from './repro-count.js'
import { javascriptLiteral } from './javascript-literal.js'
import { validReproUrlPath } from './repro-url-path.js'

function quoted(value: string): string {
  return javascriptLiteral(value)
}

function playwrightKey(key: string): string {
  return key
    .split('+')
    .map((part) => part === 'Ctrl' ? 'Control' : part)
    .join('+')
}

function targetExpression(step: BrowserReproStep): string | null {
  // Recording validates selectors with document.querySelectorAll. Plain
  // Playwright CSS also pierces shadow roots and can select additional nodes.
  return step.target?.selector ? `page.locator(${quoted(`css:light=${step.target.selector}`)})` : null
}

export function formatReproAsPlaywright(recording: BrowserReproRecording): string {
  const supportedPath = (step: BrowserReproStep) => recording.formatVersion === 4 && step.kind === 'expect'
    && step.target === undefined && step.expectation?.condition === 'urlPath' && validReproUrlPath(step.expectation.path)
    && typeof step.expectation.observedMatch === 'boolean' && step.expectation.text === undefined && step.expectation.count === undefined
  const supportedCount = (step: BrowserReproStep) => (recording.formatVersion === 3 || recording.formatVersion === 4) && step.expectation?.condition === 'count'
    && typeof step.expectation.observedMatch === 'boolean' && validReproCount(step.expectation.count) && validReproCountSelector(step.target?.selector) && step.expectation.text === undefined
  const supportedExpectation = (step: BrowserReproStep) => supportedPath(step) || step.kind === 'expect' && Boolean(step.target?.selector)
    && (supportedCount(step) || step.expectation?.condition === 'visible' || step.expectation?.condition === 'hidden' || step.expectation?.condition === 'checked' || step.expectation?.condition === 'unchecked'
      || (step.expectation?.condition === 'text' && typeof step.expectation.text === 'string'))
  const lines = [
    recording.steps.some(step => step.expectation || (step.kind === 'input' && step.target?.tag === 'select' && step.target.selector))
      ? "import { test, expect } from '@playwright/test'" : "import { test } from '@playwright/test'",
    '',
    '// Generated by Hronaut from a privacy-safe human reproduction timeline.',
    '// Review selectors, provide redacted inputs through environment variables, and add assertions before running.',
    ...(recording.active ? ['// WARNING: The recording was still active when this skeleton was exported.'] : []),
    ...(recording.truncated ? ['// WARNING: The recording reached its step limit, so the flow is incomplete.'] : []),
    `test(${quoted(`reproduce: ${recording.title || 'recorded issue'}`)}, async ({ page }) => {`
  ]

  if (recording.truncated) {
    lines.push(`  throw new Error(${quoted('TODO: Complete the truncated recording before running this test')})`)
  }

  if (!recording.steps.length) lines.push('  // TODO: Record the reproduction steps before running this test.')

  for (const step of recording.steps) {
    const target = targetExpression(step)
    if (supportedPath(step)) {
      lines.push(`  await expect(page).toHaveURL(url => ['http:', 'https:'].includes(url.protocol) && url.pathname === ${quoted(step.expectation!.path!)})`)
    } else if (step.kind === 'expect' && target && step.expectation) {
      const expectation = step.expectation
      if (supportedCount(step)) {
        lines.push(`  await expect(${target}).toHaveCount(${expectation.count})`)
      } else if (expectation.condition === 'text' && typeof expectation.text === 'string') {
        lines.push(`  await expect(${target}).toHaveText(${quoted(expectation.text)})`)
      } else if (expectation.condition === 'visible' || expectation.condition === 'hidden') {
        // A recorded hidden checkpoint refers to an existing, unique element.
        // Playwright's toBeHidden also passes when the locator finds nothing.
        if (expectation.condition === 'hidden') lines.push(`  await expect(${target}).toHaveCount(1)`)
        lines.push(`  await expect(${target}).${expectation.condition === 'visible' ? 'toBeVisible' : 'toBeHidden'}()`)
      } else if (expectation.condition === 'checked' || expectation.condition === 'unchecked') {
        // Recording rejects mixed native controls. Playwright's binary matcher
        // reads checked alone, so preserve that boundary explicitly on replay.
        lines.push(`  await expect(${target}).toHaveJSProperty('indeterminate', false)`)
        lines.push(`  await expect(${target}).${expectation.condition === 'unchecked' ? 'not.' : ''}toBeChecked()`)
      } else {
        const todo = `TODO: Recreate unsupported expectation at step ${step.index}`
        lines.push(`  // ${todo}`, `  throw new Error(${quoted(todo)})`)
      }
    } else if (step.kind === 'navigate') {
      lines.push(`  await page.goto(${quoted(step.url)})`)
    } else if (step.kind === 'click' && target) {
      lines.push(`  await ${target}.click()`)
    } else if (step.kind === 'input' && target) {
      const variable = `reproInput${step.index}`
      const environmentName = `HRONAUT_REPRO_INPUT_${step.index}`
      const selectTypeAhead = step.target?.tag === 'select'
      if (selectTypeAhead) lines.push('  // Supply reviewed type-ahead text for this native select, not an option value; review timing and selection state.')
      lines.push(
        `  const ${variable} = process.env.${environmentName}`,
        `  if (${variable} === undefined) throw new Error(${quoted(`Set ${environmentName} to a safe test value before running this reproduction`)})`,
        ...(selectTypeAhead ? [
          `  await expect(${target}).toBeEnabled()`,
          `  await ${target}.focus()`,
          `  await expect(${target}).toBeFocused()`
        ] : []),
        `  await ${target}.${selectTypeAhead ? 'pressSequentially' : 'fill'}(${variable})`
      )
    } else if (step.kind === 'key' && step.key && (!step.target || target)) {
      const action = `${target ?? 'page.keyboard'}.press(${quoted(playwrightKey(step.key))})`
      lines.push(`  await ${action}`)
    } else if (step.kind === 'scroll' && step.scroll) {
      lines.push(`  await page.evaluate(({ x, y }) => window.scrollTo(x, y), ${javascriptLiteral(step.scroll)})`)
    } else {
      const todo = `TODO: Recreate step ${step.index}: ${step.kind}`
      lines.push(`  // ${todo}`, `  throw new Error(${quoted(todo)})`)
    }
  }

  // An earlier checkpoint cannot establish the outcome of subsequent actions.
  const finalStep = recording.steps.at(-1)
  lines.push(
    '',
    ...(finalStep && supportedExpectation(finalStep)
      ? []
      : [`  throw new Error(${quoted('TODO: replace this line with an assertion for the expected failure or corrected behavior')})`]),
    '})',
    ''
  )
  return lines.join('\n')
}
