import { clientConfigurations } from '../shared/client-configuration.js'
import { localeMessages } from '../shared/i18n.js'
import type { HomeBootstrap, HomePageOptions } from '../shared/home.js'
import { HOME_PAGE_STYLES } from './home-page-styles.js'
import { HOME_WORKSPACES_STYLES } from './home-workspaces-ui.js'

export function homeBootstrap(options: HomePageOptions): HomeBootstrap {
  return { locale: options.locale, guides: clientConfigurations({ ...options, platform: options.platform ?? process.platform }),
    messages: localeMessages[options.locale], dashboard: options.initialState,
    workspaces: options.workspaces ?? { mcpTabGroups: [], savedTabGroups: [], tabs: [], activeTabId: null, allHumanInteractionLocked: false } }
}
const escapeHtml = (value: string): string => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')

/** Static, escaped document only. All interactions live in the typed Home entry. */
export function renderHomePage(options: HomePageOptions, assets = { script: '/home.js', styles: [] as string[] }): string {
  const data = homeBootstrap(options)
  const home = data.messages.home
  const library = data.messages.workspaceLibrary
  const h = escapeHtml
  const copy = (target: string, label = home.connect.copy): string => `<button class="copy-button" type="button" data-copy-target="${target}">${h(label)}</button>`
  const securityNote = options.authenticationDisabled ? home.security.disabled : options.tokenPath ? home.security.tokenFile.replace('{path}', options.tokenPath) : home.security.tokenEnvironment
  return `<!doctype html>
<html lang="${options.locale}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${h(home.title)}</title><style>${HOME_PAGE_STYLES}${HOME_WORKSPACES_STYLES}</style>${assets.styles.map(path => `<link rel="stylesheet" href="${h(path)}">`).join('')}</head>
<body><main class="page">
<header class="hero"><div class="hero-copy"><div class="brand"><span class="mark">H</span> ${h(home.brand)}</div><h1 id="home-view-title">${h(library.heading)}</h1><p id="home-view-description" class="hero-description">${h(library.description)}</p></div>
<div class="hero-status" aria-live="polite"><span id="server-state" class="status-label"></span><strong id="active-count" class="status-value"></strong><span id="request-count" class="status-detail"></span></div></header>
<section id="home-onboarding" class="panel onboarding" hidden aria-labelledby="onboarding-title">
<h2 id="onboarding-title">${h(home.connect.heading)}</h2><p>${h(home.connect.description)}</p>
<ol><li id="onboarding-client">${h(home.journey.setup)}</li><li id="onboarding-connection">${h(home.connect.verify)}</li><li id="onboarding-probe">${h(home.firstRun.heading)}</li><li>${h(data.messages.workspaceEditor.create)}</li></ol>
<button class="workspace-primary" type="button" data-open-view="connect">${h(home.connect.heading)}</button></section>
<nav class="home-navigation" role="tablist" aria-label="${h(home.navigation.label)}">
${(['workspaces', 'connect', 'overview', 'tools'] as const).map((view, index) => `<button id="home-tab-${view}" type="button" role="tab" data-home-view="${view}" ${view === 'connect' ? 'data-open-setup' : ''} aria-selected="${index === 0}" tabindex="${index === 0 ? 0 : -1}" aria-controls="home-${view}">${h(view === 'workspaces' ? library.title : home.navigation[view])}</button>`).join('')}</nav>
<section id="home-workspaces" class="home-view" role="tabpanel" aria-labelledby="home-tab-workspaces">
<div class="workspace-toolbar"><label class="search-field"><span>${h(library.search)}</span><input id="workspace-search" type="search" autocomplete="off" aria-controls="workspace-grid"></label><button type="button" class="workspace-primary" data-workspace-action="create">${h(data.messages.workspaceEditor.create)}</button><button type="button" data-workspace-action="templates">${h(data.messages.workspaceTemplates.title)}</button></div>
<div class="workspace-feedback"><p id="workspace-notice" role="status"></p><button id="workspace-undo" type="button" hidden>${h(library.undo)}</button></div><p id="workspace-error" role="alert" hidden></p>
<div class="workspace-collections" role="tablist" aria-label="${h(library.views)}"><button id="workspaces-open" type="button" role="tab" aria-selected="true" aria-controls="workspace-grid">${h(library.open)}</button><button id="workspaces-archived" type="button" role="tab" aria-selected="false" aria-controls="workspace-grid" tabindex="-1">${h(library.archived)}</button></div><p id="workspace-hint"></p><div id="workspace-grid" role="tabpanel" aria-labelledby="workspaces-open"></div></section>
<section id="home-connect" class="home-view" role="tabpanel" aria-labelledby="home-tab-connect" tabindex="0" hidden><div class="connect-layout"><section id="setup" class="panel setup-panel" aria-label="${h(home.journey.setup)}">
<header class="panel-heading"><h2 id="connect-title">${h(home.connect.agentsLabel)}</h2><span class="count">${h(home.connect.clients.replace('{count}', new Intl.NumberFormat(options.locale).format(data.guides.length)))}</span></header>
<div class="agent-layout"><div class="guide-picker"><label class="search-field"><span>${h(home.journey.searchAgents)}</span><input id="agent-search" type="search" autocomplete="off" aria-controls="agent-list"></label><nav id="agent-list" class="agents" aria-label="${h(home.connect.agentsLabel)}"></nav><p id="agent-empty" class="filter-empty" role="status" hidden>${h(home.journey.noAgents)}</p></div>
<div class="guide"><span class="guide-kicker">${h(home.connect.instructions)}</span><h3 id="guide-name"></h3><p id="guide-note" class="guide-note"></p><div id="guide-location" class="location"></div><div class="code-wrap"><pre tabindex="0"><code id="guide-code"></code></pre>${copy('guide-code')}</div>
<div id="guide-setup" class="verify" hidden><span class="verify-label">${h(home.connect.beforeLaunch)}</span><code id="guide-setup-command"></code>${copy('guide-setup-command')}</div>
<div id="guide-verify" class="verify" hidden><span class="verify-label">${h(home.connect.verify)}</span><code id="guide-verify-command"></code>${copy('guide-verify-command')}</div>
<div class="guide-doc-action"><button type="button" data-agent-guide aria-describedby="guide-open-status"></button><span id="guide-open-status" class="action-status" role="status" aria-live="polite"></span></div>
${options.authenticationDisabled ? `<div id="guide-primary-action" class="guide-primary-action" hidden><button type="button" data-vscode-install>${h(home.connect.openVsCode)}</button><span id="guide-primary-status" class="guide-primary-status" aria-live="polite"></span></div>` : ''}<p class="security">${h(securityNote)}</p></div></div></section>
<aside class="connect-aside"><section class="connection-check"><span class="section-kicker">${h(home.journey.verify)}</span><h2>${h(home.connect.verify)}</h2><p id="connection-note" class="connection-note" role="status">${h(home.journey.waiting)}</p><p id="connection-probe" role="status"></p><button type="button" class="text-action" data-open-view="overview">${h(home.navigation.overview)} →</button></section>
<section class="panel first-run" aria-labelledby="first-run-title"><div><span class="first-run-kicker">${h(home.journey.tryTask)}</span><h2 id="first-run-title">${h(home.firstRun.heading)}</h2><p>${h(home.firstRun.description)}</p></div><div class="code-wrap"><pre tabindex="0"><code id="first-run-prompt">${h(home.firstRun.prompt)}</code></pre>${copy('first-run-prompt', home.firstRun.copy)}</div><button type="button" data-open-view="workspaces">${h(data.messages.workspaceEditor.create)}</button></section></aside></div></section>
<section id="home-overview" class="home-view" role="tabpanel" aria-labelledby="home-tab-overview" tabindex="0" hidden>
<div class="impact-grid"><div class="impact"><strong id="completed-count">0</strong><span>${h(home.activity.tabActionsCompleted)}</span></div><div class="impact"><strong id="tool-types-count">0</strong><span>${h(home.activity.toolsUsed)}</span></div><div class="impact"><strong id="success-rate">—</strong><span>${h(home.activity.successfulActions)}</span></div></div>
<div class="overview-layout"><section id="activity" class="panel activity" aria-labelledby="activity-title" tabindex="-1"><header class="panel-heading"><div><h2 id="activity-title">${h(home.activity.heading)}</h2><p>${h(home.activity.description)}</p></div><span id="activity-count" class="count"></span></header><div class="activity-layout"><div class="activity-column"><h3>${h(home.activity.recent)}</h3><div id="activity-list" class="activity-list"></div><p class="privacy-note">${h(home.activity.privacy)}</p></div></div></section>
<div class="overview-side"><section class="panel readiness" aria-labelledby="readiness-title"><header class="panel-heading"><div><h2 id="readiness-title">${h(home.readiness.heading)}</h2><p>${h(home.readiness.description)}</p></div></header><div class="readiness-body"><div id="readiness-checks" class="readiness-checks"></div><label class="readiness-inventory" for="readiness-tool-inventory">${h(home.readiness.inventory)}</label><textarea id="readiness-tool-inventory" rows="4" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="${h(home.readiness.inventoryPlaceholder)}"></textarea><div class="readiness-actions"><button id="readiness-verify" class="copy-button" type="button">${h(home.readiness.verifyInventory)}</button>${copy('readiness-report', home.readiness.copyReport)}</div><pre class="readiness-report" tabindex="0" aria-label="${h(home.readiness.reportLabel)}"><code id="readiness-report"></code></pre><p class="privacy-note">${h(home.readiness.privacy)}</p></div></section>
<section class="panel" aria-labelledby="connections-title"><header class="panel-heading"><div><h2 id="connections-title">${h(home.connections.heading)}</h2><p>${h(home.connections.description)}</p></div><span id="client-count" class="count"></span></header><div id="connections" class="connections-body"></div></section></div></div></section>
<section id="home-tools" class="home-view" role="tabpanel" aria-labelledby="home-tab-tools" tabindex="0" hidden><section id="tools" class="panel tools" tabindex="-1" aria-labelledby="tools-title"><header class="panel-heading"><h2 id="tools-title">${h(home.navigation.tools)}</h2><span id="tool-count" class="count"></span></header><p class="connection-note">${h(home.tools.description)}</p><label class="search-field"><span>${h(home.journey.searchTools)}</span><input id="tool-search" type="search" autocomplete="off" aria-controls="tool-grid"></label><p id="tool-empty" class="filter-empty" role="status" hidden>${h(home.journey.noTools)}</p><div id="tool-grid" class="tool-grid"></div></section></section>
<div class="home-bottom"><div class="endpoint"><span class="endpoint-label">${h(home.endpoint)}</span><code id="endpoint">${h(options.endpoint)}</code>${copy('endpoint', home.copyUrl)}</div>
<details class="support-panel"><summary>${h(home.support.troubleshoot)}</summary><aside class="support-card"><span id="support-kicker">${h(home.support.kicker)}</span><h3 id="support-heading">${h(home.support.heading)}</h3><p id="support-message">${h(home.support.message)}</p>
<button id="support-troubleshoot" type="button" data-setup-help aria-describedby="support-help-status">${h(home.support.troubleshoot)}</button><div id="support-help-status" class="action-status" role="status" aria-live="polite"></div><button id="support-feedback" class="secondary" type="button" data-setup-feedback aria-describedby="support-feedback-status">${h(home.support.reportTrouble)}</button><div id="support-feedback-status" class="action-status" role="status" aria-live="polite"></div>
<button id="support-recommend" class="secondary" type="button" data-copy-target="support-recommend-message" hidden>${h(home.support.recommend)}</button><span id="support-recommend-message" hidden>${h(home.support.recommendMessage)}</span><small id="support-welcome">${h(home.support.helpPrivacy)}</small><small id="support-feedback-privacy">${h(home.support.feedbackPrivacy)}</small><small id="support-recommend-privacy" hidden>${h(home.support.recommendPrivacy)}</small></aside></details></div>
<p id="copy-status" role="status" aria-live="polite"></p><footer class="footer"><span>${h(home.footer)}</span><span id="server-version">Hronaut ${h(options.initialState.version)}</span></footer></main>
<script id="home-bootstrap" type="application/json">${JSON.stringify(data).replaceAll('<', '\\u003c')}</script><script type="module" src="${h(assets.script)}"></script></body></html>`
}
