import { execFileSync } from 'node:child_process'
import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { build } from 'esbuild'
import { parse } from 'yaml'
import licenseApi from '../src/shared/license-api-fixtures.json' with { type: 'json' }

const root = resolve(process.env.HRONAUT_CONTRACT_SOURCE || '.')
const output = resolve(process.argv[2] || 'dist/hronaut-public-contract.json')
const { version } = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8')) as { version: string }
const sourceRevision = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim()
const releaseRevision = execFileSync('git', ['rev-parse', `v${version}^{commit}`], { cwd: root, encoding: 'utf8' }).trim()
if (sourceRevision !== releaseRevision) throw new Error('Public contracts must identify an exact tagged release')
if (execFileSync('git', ['status', '--porcelain', '--untracked-files=no'], { cwd: root, encoding: 'utf8' }).trim() && !process.argv.includes('--development')) {
  throw new Error('Public contracts require a clean tagged checkout')
}
const legacy = process.argv.includes('--legacy')
const packaging = parse(await readFile(resolve(root, 'electron-builder.yml'), 'utf8')) as Record<string, { target: { target: string; arch: string[] }[] }>
const bundled = await build({ absWorkingDir: root, bundle: true, write: false, platform: 'node', format: 'esm',
  stdin: { resolveDir: root, contents: `${legacy
    ? `import { renderHomePage } from './src/main/home-page.ts'; export function configurations(options) { const html = renderHomePage({ ...options, initialState: { version: '${version}' } }); return JSON.parse(html.match(/const guides = (.+);\\n {4}const messages =/)[1]); }`
    : `export { clientConfigurations as configurations } from './src/shared/client-configuration.ts';`}
     export { CommercialLicenseClient } from './src/main/commercial-license-client.ts';
     export { BROWSER_TOOL_CATALOG as tools } from './src/main/mcp/tool-catalog.ts';` } })
const module = await import(`data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0]!.text).toString('base64')}`) as {
  configurations(options: object): { id: string; name: string; note: string; location: string; code: string; setupCommand?: string; verifyCommand?: string }[]
  tools: { name: string; title?: string; category: string; description: string; annotations?: object }[]
  CommercialLicenseClient: new (url: string, request: typeof fetch) => { validate(key: string, instance: string): Promise<unknown> }
}
const client = new module.CommercialLicenseClient('https://license.example.test/api/license', async () => Response.json(licenseApi.active))
if (JSON.stringify(await client.validate('EXAMPLE-KEY', 'inst_abcdefgh1234')) !== JSON.stringify(licenseApi.active)) throw new Error('Release does not support license API fixture')
const clients = ['linux', 'win32'].flatMap(platform => [true, false].map(authenticationDisabled => ({
  platform, authenticationDisabled,
  templates: module.configurations({ locale: 'en-US', endpoint: '{{endpoint}}', platform,
    authenticationDisabled, tokenPath: authenticationDisabled ? undefined : '{{tokenFile}}' })
})))
const manifest = {
  schemaVersion: 1, product: 'hronaut', release: `v${version}`, sourceRevision,
  provenance: legacy ? 'Generated from tagged Home templates before public-contract export existed.' : 'Generated by the immutable tagged release workflow.',
  platforms: ['win', 'mac', 'linux'].map(os => ({ os, targets: packaging[os]!.target })),
  clients, licenseApi, tools: module.tools.map(({ name, title, category, description, annotations }) => ({ name, title, category, description, annotations }))
}
await mkdir(dirname(output), { recursive: true })
await writeFile(output, `${JSON.stringify(manifest, null, 2)}\n`)
console.log(`Exported ${manifest.release}: ${module.tools.length} tools, ${clients[0]!.templates.length} client templates to ${output}`)
